/*
 HTML5 3D Flipping Gallery 2
 Version: 2.0.1
 (c) 2015 DMXzone.com
 @build 05-05-2015 16:30:37
*/
(function(c){function q(b){for(var c=document.createElement("div").style,d=["","-webkit","-moz","-o","-ms"],h=["","Webkit","Moz","O","ms"],t=0;t<h.length;t++)if(h[t]+b in c)return d[t]+b.replace(/([A-Z])/g,"-$1").toLowerCase();return!1}var N={animationDuration:400,rotation:"random",maxRotation:10,random:!1,shuffle:!1,shufflePlacement:"uniform",zoomTrigger:"hover",zoomFactor:1.2,flipTrigger:"click",flipEffect:"default",flipDirection:"left",flipRotation:0,singleActive:!1,perspective:800},D=q("Transition"),
d=q("Transform"),O=q("TransformOrigin"),J=q("Perspective"),F=q("TransformStyle"),P=q("BackfaceVisibility"),n=!1!==J,h=1==n;c(function(){if(n&&"webkitPerspective"in c("body").get(0).style){var b=c('<div id="csstransform3d"></div>'),d=c('<style media="(transform-3d),(-webkit-transform-3d)">div#csstransform3d{position:absolute;left:9px;height:3px;}</style>');c("body").append(b);c("head").append(d);n=9===b[0].offsetLeft&&3===b[0].offsetHeight;b.remove();d.remove()}h&&(b=c('<div style="'+F+': preserve-3d;"></div>'),
c("body").append(b),h="preserve-3d"==b.css(F).toLowerCase(),b.remove())});c.fn.dmx3DFlipGallery=function(b){function e(c){var d=c.data("translate")||[0,0],e=c.data("scale")||1,l=c.data("rotateX")||0,s=c.data("rotateY")||0;c=c.data("rotateZ")||c.data("rotate")||0;/^\d+$/.test(d[0])&&(d[0]+="px");/^\d+$/.test(d[1])&&(d[1]+="px");return n?(h?"":"perspective("+b.perspective+"px) ")+"translate3D("+d[0]+","+d[1]+",0px) scale("+e+") rotateX("+l+"deg) rotateY("+s+"deg) rotateZ("+c+"deg)":"translate("+d[0]+
"px,"+d[1]+"px) scale("+e+") rotate("+c+"deg)"}b=c.extend({},N,b);var l=Math.random,s=Math.floor;return this.each(function(){function t(){var a=!0;m.find("img").each(function(){if(0==this.width||0==this.height)a=!1});a?(m.find("img").mousedown(function(c){c.preventDefault()}),n?(/^top|bottom$/i.test(b.flipDirection)?c(".dmx3DFlipPhotoBack").data("rotateX",180):c(".dmx3DFlipPhotoBack").data("rotateY",180),c(".dmx3DFlipPhotoBack").each(function(){c(this).css(d,e(c(this).parent())+" "+e(c(this)))}),
c(".dmx3DFlipPhotoFront").css(d,e(c(this).parent())+" "+e(c(this)))):c(".dmx3DFlipPhotoBack").hide(),k.each(function(g){var a=c(this),f=a.width(),k=a.height(),r=a.wrap('<div class="dmx3DFlipPhotoWrapper" />').parent();if(n&&(h&&(r.css(J,b.perspective+"px"),a.css(F,"preserve-3d")),a.children().css(P,"hidden"),"slide"==b.flipEffect&&h)){var y="center center";switch(b.flipDirection){case "top":y="center top";break;case "left":y="left center";break;case "bottom":y="center bottom";break;case "right":y=
"right center"}a.css(O,y)}a.data("rotation",a.data("rotation")||b.rotation);"random"==a.data("rotation")&&a.data("rotation",s(l()*(2*b.maxRotation+1))-b.maxRotation);d&&r.data("rotate",parseInt(a.data("rotation")));if(b.shuffle)switch(r.css("position","absolute"),b.shufflePlacement){case "jittered":f=g%p;g=s(g/p);f=s(f*z+l()*(z/2)+z/4);g=s(g*A+l()*(A/2)+A/4);r.css({left:f,top:g});break;default:r.css({left:s(l()*(B-f)),top:s(l()*(C-k))})}else r.css({position:"relative",display:"inline-block"});d&&
(r.css(d,e(r)),a.css(d,e(a)))}),D&&(k.css(D,d+" "+b.animationDuration+"ms").parent().css(D,d+" "+b.animationDuration+"ms"),n&&!h&&k.children().css(D,d+" "+b.animationDuration+"ms")),b.random&&(k.shuffle(),k=m.find(".dmx3DFlipPhoto")),m.off(".dmx3DFlipGallery").on("fakeclick.dmx3DFlipGallery",".dmx3DFlipPhoto",function(a){a=c(this);"click"==b.zoomTrigger&&(d&&(1==a.data("scale")?K(a):G(a)),b.singleActive&&G(k.not(a).filter(".dmx3DFlipPhotoActive")));"click"==b.flipTrigger&&(a.hasClass("dmx3DFlipPhotoFlipped")?
H(a):L(a),b.singleActive&&H(k.not(a).filter(".dmx3DFlipPhotoActive")));b.singleActive&&k.not(a).filter(".dmx3DFlipPhotoActive").removeClass("dmx3DFlipPhotoActive");a.addClass("dmx3DFlipPhotoActive")}).on("mouseenter.dmx3DFlipGallery",".dmx3DFlipPhoto",function(a){a=c(this);"hover"==b.zoomTrigger&&K(a);"hover"==b.flipTrigger&&L(a)}).on("mouseleave.dmx3DFlipGallery",".dmx3DFlipPhoto",function(a){a=c(this);"hover"==b.zoomTrigger&&G(a);"hover"==b.flipTrigger&&H(a)}).on("mousedown.dmx3DFlipGallery touchstart.dmx3DFlipGallery",
".dmx3DFlipPhotoWrapper",function(a){"touchstart"==a.type&&(a.preventDefault(),a=a.originalEvent.touches[0]);var d=c(this),e=!1,f=d.position(),r=a.pageX-f.left,l=a.pageY-f.top;q(d);if(b.shuffle)c("body").on("mousemove.dmx3DFlipGallery touchmove.dmx3DFlipGallery",function(a){"touchmove"==a.type&&(a=a.originalEvent.touches[0]);e=!0;d.css({left:a.pageX-r,top:a.pageY-l})});c("body").on("mouseup.dmx3DFlipGallery touchend.dmx3DFlipGallery",function(a){c("body").off(".dmx3DFlipGallery");if(!e){if("touchend"==
a.type&&a.srcElement){var b=a.originalEvent,g=document.createEvent("MouseEvents");g.initMouseEvent("click",!0,!0,b.view,1,b.changedTouches?b.changedTouches[0].screenX:b.screenX,b.changedTouches?b.changedTouches[0].screenY:b.screenY,b.changedTouches?b.changedTouches[0].clientX:b.clientX,b.changedTouches?b.changedTouches[0].clientY:b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,0,null);a.srcElement.dispatchEvent(g)}d.children().trigger("fakeclick.dmx3DFlipGallery")}})}),m.removeClass("dmx3DFlipGalleryLoading")):
setTimeout(t,100)}function q(a){var b,d=parseInt(a.css("z-index"))||0;a.siblings().each(function(){b=parseInt(c(this).css("z-index"))||0;d<=b&&(d=b+1)});a.css("z-index",d)}function K(a){d&&(a.data("scale",b.zoomFactor),n&&!h?a.children().each(function(){c(this).css(d,e(a)+" "+e(c(this)))}):a.css(d,e(a)));q(a.parent())}function G(a){d&&(a.data("scale",1),n&&!h?a.children().each(function(){c(this).css(d,e(a)+" "+e(c(this)))}):a.css(d,e(a)))}function H(a){var g=a.parent();a.removeClass("dmx3DFlipPhotoFlipped");
d&&g.data("rotate",a.data("rotation")).css(d,e(g));n?("slide"==b.flipEffect&&h&&a.data("translate",[0,0]),/^top|bottom$/i.test(b.flipDirection)?a.data("rotateX",0):a.data("rotateY",0),h?a.css(d,e(a)):a.children().each(function(){c(this).css(d,e(a)+" "+e(c(this)))})):a.find(".dmx3DFlipPhotoBack").hide()}function L(a){var g=a.parent();a.addClass("dmx3DFlipPhotoFlipped");d&&("random"==b.flipRotation?g.data("rotate",s(l()*(2*b.maxRotation+1))-b.maxRotation).css(d,e(g)):"none"!=b.flipRotation&&g.data("rotate",
parseInt(b.flipRotation)).css(d,e(g)));if(n){var f=/^top|left$/i.test(b.flipDirection)?-180:180;if("slide"==b.flipEffect&&h)switch(b.flipDirection){case "top":a.data("translate",[0,"100%"]);break;case "left":a.data("translate",["100%",0]);break;case "bottom":a.data("translate",[0,"-100%"]);break;case "right":a.data("translate",["-100%",0])}/^top|bottom$/i.test(b.flipDirection)?a.data("rotateX",f):a.data("rotateY",f);h?a.css(d,e(a)):a.children().each(function(){c(this).css(d,e(a)+" "+e(c(this)))})}else a.find(".dmx3DFlipPhotoBack").show();
q(g)}var m=c(this),k=m.find(".dmx3DFlipPhoto"),B=m.width(),C=m.height(),u=k.length,p=u,f=1,v=0,w=0,z=0,A=0;m.addClass("dmx3DFlipGalleryLoading");if(b.repeatElement&&b.dynSlides){var E=c.dmxDataBindings;E?E.globalScope.watch(b.repeatElement,function(a){m.empty();if(a){c.each(a,function(a,d){var e={},f=new E.Scope;f.set(d);for(var g in b.dynSlides)"string"===typeof b.dynSlides[g]&&(e[g]=E.$parseTemplate(b.dynSlides[g],f)),"width"==g&&b.dynSlides[g]&&(e[g]=b.dynSlides[g]),"height"==g&&b.dynSlides[g]&&
(e[g]=b.dynSlides[g]);if(e.url){f=c("<div>").addClass("dmx3DFlipPhoto");g=c("<div>").addClass("dmx3DFlipPhotoFront");var l=c("<div>").addClass("dmx3DFlipPhotoBack"),h=c('<a href="javascript: void(0);">'),k=c('<img src="'+e.url+'" border="0"'+(e.id?' id="'+e.id+'"':"")+(e.width?' width="'+e.width+'"':"")+(e.height?' height="'+e.height+'"':"")+">");h.append(k);g.append(h);e.rotation&&g.attr("data-rotate",e.rotation);e.title&&(g.append("<h4>"+e.title+"</h4>"),l.append("<h4>"+e.title+"</h4>"));e.description&&
l.append("<p>"+e.description+"</p>");f.append(g).append(l);m.append(f)}});k=m.find(".dmx3DFlipPhoto");p=u=k.length;f=1;w=v=0;if("jittered"==b.shufflePlacement){var d=1;a=0;for(k.each(function(a){a=c(this).width();var b=c(this).height();v=Math.max(v,a);w=Math.max(w,b);d+=a/b;d/=2});f<u;){var e=B/p/(C/f);if(e>d){if(1==f)break;Math.abs(d-e)>Math.abs(d-a)&&(--f,p=Math.ceil(u/f));break}a=e;f+=1;p=Math.ceil(u/f)}}z=(B-v)/p;A=(C-w)/f;t()}}):alert("HTML5 Data Bindings is required!")}else{if("jittered"==b.shufflePlacement){var x=
1,M=0;for(k.each(function(a){a=c(this).width();var b=c(this).height();v=Math.max(v,a);w=Math.max(w,b);x+=a/b;x/=2});f<u;){var I=B/p/(C/f);if(I>x){if(1==f)break;Math.abs(x-I)>Math.abs(x-M)&&(--f,p=Math.ceil(u/f));break}M=I;f+=1;p=Math.ceil(u/f)}}z=(B-v)/p;A=(C-w)/f;t()}})};c.fn.shuffle=function(){var b=this.get(),d=c.map(b,function(){var d;d=b.length;d=Math.floor(Math.random()*d);var e=c(b[d]).clone(!0)[0];b.splice(d,1);return e});this.each(function(b){c(this).replaceWith(c(d[b]))});return c(d)}})(window.jQuery||
window.Zepto);
